# Generated by Django 5.2.12 on 2026-08-29 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=200, unique=True)),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('allowed_fields', models.JSONField(blank=True, default=list)),
                ('allowed_values', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ObjectGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=200, unique=True)),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('conditions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RoleEndpointGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'key'), name='permkit_unique_role_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='RoleFieldGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_bindings', to='permkit.fieldgrant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'grant'), name='permkit_unique_role_field')],
            },
        ),
        migrations.CreateModel(
            name='RoleObjectGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_bindings', to='permkit.objectgrant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'grant'), name='permkit_unique_role_object')],
            },
        ),
    ]
