# Generated by Django 5.2.12 on 2026-09-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permkit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('last_seen_at', models.DateTimeField()),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('targets', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='RegisteredObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('last_seen_at', models.DateTimeField()),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('key', models.SlugField(max_length=200, unique=True)),
                ('model_label', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='RegisteredFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('last_seen_at', models.DateTimeField()),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('open_params', models.JSONField(blank=True, default=dict)),
                ('multi_valued', models.BooleanField(default=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='permkit.registeredobject')),
            ],
            options={
                'ordering': ('object__key', 'key'),
            },
        ),
        migrations.CreateModel(
            name='RegisteredFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('last_seen_at', models.DateTimeField()),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(max_length=100)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='permkit.registeredobject')),
            ],
            options={
                'ordering': ('object__key', 'key'),
                'constraints': [models.UniqueConstraint(fields=('object', 'key'), name='permkit_unique_field_group')],
            },
        ),
        migrations.CreateModel(
            name='RegisteredScopePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('last_seen_at', models.DateTimeField()),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('action_key', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=500)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_points', to='permkit.registeredobject')),
            ],
            options={
                'ordering': ('object__key', 'action_key', 'target'),
                'constraints': [models.UniqueConstraint(fields=('object', 'action_key', 'target'), name='permkit_unique_scope_point')],
            },
        ),
    ]
