# Generated by Django 5.2.12 on 2026-09-02 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permkit', '0002_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this permission is for, in the words of whoever grants it.')),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='PermissionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_by', to='permkit.registeredaction')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='permkit.permission')),
            ],
            options={
                'ordering': ('action__key',),
            },
        ),
        migrations.CreateModel(
            name='PermissionFieldGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(max_length=100)),
                ('allowed_values', models.JSONField(blank=True, default=dict)),
                ('field_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_by', to='permkit.registeredfieldgroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_grants', to='permkit.permission')),
            ],
            options={
                'ordering': ('field_group__object__key', 'action_key', 'field_group__key'),
            },
        ),
        migrations.CreateModel(
            name='PermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, help_text="How this rule reads in a list, e.g. 'own warehouse, assigned to me'.", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='permkit.registeredobject')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='permkit.permission')),
            ],
            options={
                'ordering': ('permission__key', 'order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PermissionRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_by', to='permkit.registeredfilter')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='permkit.permissionrule')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_bindings', to='permkit.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permkit.role')),
            ],
            options={
                'ordering': ('role__key', 'permission__key'),
            },
        ),
        # The free-text grant tables these replace. Dropped children first:
        # the autodetector emitted RemoveField for the FKs, which fails
        # because 0001's unique constraints still reference them. Deleting
        # the whole table takes the constraints with it.
        migrations.DeleteModel(
            name='RoleFieldGrant',
        ),
        migrations.DeleteModel(
            name='RoleObjectGrant',
        ),
        migrations.DeleteModel(
            name='RoleEndpointGrant',
        ),
        migrations.DeleteModel(
            name='FieldGrant',
        ),
        migrations.DeleteModel(
            name='ObjectGrant',
        ),
        migrations.AddConstraint(
            model_name='permissionaction',
            constraint=models.UniqueConstraint(fields=('permission', 'action'), name='permkit_unique_permission_action'),
        ),
        migrations.AddConstraint(
            model_name='permissionfieldgrant',
            constraint=models.UniqueConstraint(fields=('permission', 'field_group', 'action_key'), name='permkit_unique_permission_field_grant'),
        ),
        migrations.AddConstraint(
            model_name='permissionrulecondition',
            constraint=models.UniqueConstraint(fields=('rule', 'filter'), name='permkit_unique_rule_filter'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='permkit_unique_role_permission'),
        ),
    ]
