# Generated by Django 5.2.12 on 2026-09-03 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permkit', '0003_composition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredaction',
            options={'ordering': ('key',), 'verbose_name': 'declared endpoint', 'verbose_name_plural': 'declared endpoints'},
        ),
        migrations.AlterModelOptions(
            name='registeredfieldgroup',
            options={'ordering': ('object__key', 'key'), 'verbose_name': 'declared field group', 'verbose_name_plural': 'declared field groups'},
        ),
        migrations.AlterModelOptions(
            name='registeredfilter',
            options={'ordering': ('object__key', 'key'), 'verbose_name': 'declared row filter', 'verbose_name_plural': 'declared row filters'},
        ),
        migrations.AlterModelOptions(
            name='registeredobject',
            options={'ordering': ('key',), 'verbose_name': 'declared object', 'verbose_name_plural': 'declared objects'},
        ),
        migrations.AlterModelOptions(
            name='registeredscopepoint',
            options={'ordering': ('object__key', 'action_key', 'target'), 'verbose_name': 'declared enforcement point', 'verbose_name_plural': 'declared enforcement points'},
        ),
    ]
